### ISSUE TITLE
the section about nullable types is confusing regarding strict mode

### ISSUE THREAD

**Issue by stof** [knpuniversity/php7#3]
The section about nullable types tells you that strict mode makes you think about more cases. But this is wrong. `null` is never allowed for a typehinted argument, even in weak mode. See https://3v4l.org/7i0Y8 for the proof.
btw, `is_scalar(null)` is `false` 😄

**Comment by weaverryan** [comment]
You're right - it's misleading. In fact, I don't think I was thinking about this correctly - I've clarified it quite a bit at sha: b622ee8abe3cf41704a1f6aff8169ad17e74155b

Thanks!
