### ISSUE TITLE
The doctrine Collection return type is not just hipster, but required

### ISSUE THREAD

**Issue by stof** [knpuniversity/php7#4]
The chapter about refactoring the class says that using the `Collection` interface is more hipster than typing with `ArrayCollection`. While this may be true, it is the bad argument.

Doctrine gives you only the guarantee that your property contains a `Collection`. It does not always use an ArrayCollection. And actually, when loading an entity from the DB, it actually *always* use a `Doctrine\ORM\PersistentCollection`, which allow the ORM to lazy-load it and to track changes. And this class does not extend `Doctrine\Common\Collections\ArrayCollection`. It only implement the interface (it actually decorates an `ArrayCollection` internally)

**Comment by weaverryan** [comment]
This is not something I realized! It makes perfect sense now - this is definitely a mistake! I've updated that text at sha: 587844262c0dc9419a4f219be2aa7f2aaae4fede

Thank you!
